language: ruby
rvm:
- 2.2
- jruby
deploy:
  api_key:
    secure: G7sjUHBKZextqRIdrPcrbPB/apDdH+FKglGrWf0o8JlyaAjn+j6MumdCftoklfWmTXU9d22p3vyGIedNxSV94DonolCa+bUjBIRBLDL0hl3yajcXOzLq+HT0Nhn1dmrxxuuIMgk5swP/ogeQnrC8Al5oWL2Wi1gE+fnTqyJaQrle7YhilpZH/j1GOxsrglLsa0XWjN7T9xNHNT2puRe997X5Dgw2q1xFeFgW6QV9KGZGHcilfutX4g2qXwObUeQo6Q/wlRv/XgVS9nEByx74Xb77iQtEvhOi10PR70oqZu9C5ESd+HmqaxpVyeyaCx6cXdImka+M4X7fb+57Dh3MOwu1moNILAy2JrLvYHpPGompCUCtszbDiTAz3YQvfTO8Kvhdesf2wROQk2PzbyedKc9Oyac+bBPgy5ayRvavDCxV56xsb7m7XFx4evlS/D5fmxZvFgiyVd6NGC/6GsdrDqJboBnufA1vKRn5OLnygXDlGFPWFI5Riic8SKTmqmaZKUKlcSDAKrKQkMIq3aPlNrVO5tDNkm0lby6wEn/MDWD3Cwi9Q/+qZPxKtjO9TSyNPVg8fROLAoeYRc5pgO4s5s1e/+KiN1+Bys/uCXrdaZWT32QTuzi7COflxrYjTV8dBFJfasNGzWiOEYjbVYpWN7T+9sfJ6ZR1mD9qiJZ+5z0=
