language: ruby
rvm: 2.5.0
before_script:
- bundle exec rake db:create
- bundle exec rake assets:precompile
before_install:
- gem update --system
- gem install bundler
addons:
  postgresql: 9.6
env:
- DB=pgsql
script:
- bundle exec rake db:migrate
matrix:
  fast_finish: true
deploy:
  provider: heroku
  app: pic-a-gram
  api_key:
    secure: qkrcsw1NkCdDgN+0O/2iYI6O2CT6jOj/OU0UTfy4H0hf99iKNoxqh2D33mkYTXoIGD0aOhrhJniS7ZvEiilcrAijhiI4IdlExC9gZd6LgJBF1qeV36HSYdxTaqNyJ7e0gx3QnW2L0l9gphNqWFQfyh691WzlBJ3OkqFsjD8ppTYH6wjnVwQgKgW1ld/G3Ve2Idp5hX+rQELfwSDFs/35nMWh/2RUv8cMLIbsXfbby6q8Y/FSYBaaFPmd+7do1HsjLDefjdPxL9G9Xj9XbtaDDuTxIW4PYjQxLQ1j43p3IP83T+EXILXXdq3S1lAspnExO854/KmMa3hEoB/MsQ8NszIhAdx0pSVR8owp/aY62xPkmLLkS44ckKq/AMo5lk2MdkTJ8fo+ydJyfvJZ9cR1kjOm9qDwUC9VXP1vhufPN3gFqQvbwHwTBaedMLYh84l9t+xZTUbQKPbsQMioFq3JB8f9v0qM4z7bCd7b0oi1A9+NDvODR6AOgvSPjyZbYxs0MZN7yNEz2ANhhqcr1k3D5Wmor5tTmkpTNRB5Y8AfUA8mmSDBC6V872Kd0EwJ3l+HSEGuLzN84FT5CXTDg42wbkQdqbzBo5dkISctxXeoGK4QSJD33UzJrwujlBIgLipJT64XKVq7iDcPFk+G6btytYAazC4ZBzQcIMwMAVaBWb0=
