language: ruby
rvm: 2.5.0
before_script:
- bundle exec rake db:create
- bundle exec rake assets:precompile
before_install:
- gem update --system
- gem install bundler
addons:
  postgresql: 9.6
env:
  - DB=pgsql
script:
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  app: pic-a-gram
  api_key:
    secure: "dEY1q/WlcaEDEaYiWVmte2uA3rjujDciDcHYR+9N0bapanKd58oB8P5MnsJUx6lCbfqMw4W8Ttkps+g6EBODPDr/Rcd+swSt9s836qbhpxaShtHlG18PUkWjgeWN0Xfrh/y2rtOavpygWX1hfp/JHYP3dyESS5ot4nrK79GOoDmsXz+9n2YD/Keypahixg2v4ZghYXpa8kTPwJ7LVwSuDHgbEt2ETMg13Vnjfnl1L369WUNqCbn9VVCzTPBducnRLWdzU57BB0VnMcp+TH0TqapYwPMECWPHYVaoUf6LFn4xXHWAmB+sCwJb9s8U+7zxDbWG6QUqeAgbTw+snARMMD4gSItFIPeQVdN0UTMyL2Ifm/ObyGEIF9iKNcuMoN+gUKLoyBQzMNypNw7xMlT4dHoXU16hyiYgqLbxExIwcCrVnY4923OrNxIeHdS0drAA22R8PDryLh0IylQ2wkOWJ0eMh7Z6E23leTr57YntLtbRs9UYnWntxZLPjXzAdyllXnqUn0ZgGbE5coIzBRHw02gAaBAqYC9J/U39gfLhp+NTrRW7LRAqhHeTIrJMNjFDc1YLIrZ/FYbrSMvz+qp6DaiZ75yhZDQ+OAIFickPAtNswseGgZ10GD1PskYC5A94WpS6+5J5a3f6NWZuANMJzdVyMHXAjzbHqStX2CEXfNk="
    on:
      repo: fo0s/Picagram
      branch: master